# Generated by Django 4.2.5 on 2023-09-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sel4c', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
