# Generated by Django 4.2.5 on 2023-10-04 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sel4c', '0002_activitiescompleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitiescompleted',
            options={'verbose_name': 'Activities Completed', 'verbose_name_plural': 'Activities Completed'},
        ),
    ]
