# Generated by Django 4.2.4 on 2023-10-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sel4c', '0002_activitiescompleted_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitiescompleted',
            name='is_completed',
        ),
    ]
