# Generated by Django 4.2.5 on 2023-09-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sel4c', '0002_alter_admin_email_alter_admin_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='is_superadmin',
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
