# Generated by Django 4.2.5 on 2023-10-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sel4c', '0003_alter_activitiescompleted_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'entrepreneur')},
        ),
    ]
