# Generated by Django 4.2.5 on 2023-09-25 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sel4c', '0003_remove_admin_is_superadmin_alter_admin_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'admins'},
        ),
    ]
