# Generated by Django 4.2.4 on 2023-10-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sel4c', '0004_alter_activitiescompleted_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No binario', 'No binario'), ('Prefiero no decirlo', 'Prefiero no decirlo')], max_length=255),
        ),
    ]
