# Generated by Django 4.2.5 on 2023-09-27 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sel4c', '0005_alter_activity_id_alter_answer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='username',
        ),
        migrations.AddField(
            model_name='answer',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sel4c.entrepreneur'),
        ),
    ]
