# Generated by Django 4.2.5 on 2023-09-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sel4c', '0006_remove_activity_username_answer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deliveries',
            field=models.IntegerField(default=0),
        ),
    ]
