# Generated by Django 4.2.4 on 2023-10-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sel4c', '0008_alter_answer_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='activity',
        ),
        migrations.AlterField(
            model_name='activitiescompleted',
            name='attempts',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
