# Generated by Django 4.2.4 on 2023-10-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sel4c', '0009_remove_question_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='deliveries',
        ),
    ]
