# Generated by Django 4.2.6 on 2023-10-20 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sel4c', '0010_remove_activity_deliveries'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrereneurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('result1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result6', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result7', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result8', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result9', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result10', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result11', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result12', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result13', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result14', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result15', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result16', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result17', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sel4c.activity')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sel4c.entrepreneur')),
            ],
        ),
    ]
