# Generated by Django 4.2.6 on 2023-10-20 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sel4c', '0012_remove_entrereneurprofile_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurEcomplexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sel4c.activity')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sel4c.entrepreneur')),
            ],
        ),
    ]
