# Generated by Django 4.2.6 on 2023-10-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sel4c', '0013_entrepreneurecomplexity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntrereneurProfile',
            new_name='EntrepreneurProfile',
        ),
    ]
